//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CategoryID { get; set; }
        public Nullable<double> Price { get; set; }
        public string CreatedBy { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public System.DateTime UpdateDatetime { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
